export const ADD_VISITED_VIEWS = 'ADD_VISITED_VIEWS';
export const DEL_VISITED_VIEWS = 'DEL_VISITED_VIEWS';
export const DEL_OTHERS_VIEWS = 'DEL_OTHERS_VIEWS';
export const DEL_ALL_VIEWS = 'DEL_ALL_VIEWS';